//! Path: native/nif/src/key_map.rs
//! Summary: winit KeyCode → Elixir アトム名のマッピング
//!
//! 生イベント転送用。Elixir 側でキー→意味のマッピングを行う。

use render::window::KeyCode;

macro_rules! key_map {
    ($($key:ident => $atom:literal),* $(,)?) => {
        pub fn key_code_to_atom_str(code: KeyCode) -> &'static str {
            match code {
                $(KeyCode::$key => $atom,)*
                _ => "unknown",
            }
        }
    };
}

key_map! {
    KeyA => "a",
    KeyB => "b",
    KeyC => "c",
    KeyD => "d",
    KeyE => "e",
    KeyF => "f",
    KeyG => "g",
    KeyH => "h",
    KeyI => "i",
    KeyJ => "j",
    KeyK => "k",
    KeyL => "l",
    KeyM => "m",
    KeyN => "n",
    KeyO => "o",
    KeyP => "p",
    KeyQ => "q",
    KeyR => "r",
    KeyS => "s",
    KeyT => "t",
    KeyU => "u",
    KeyV => "v",
    KeyW => "w",
    KeyX => "x",
    KeyY => "y",
    KeyZ => "z",
    Digit0 => "digit0",
    Digit1 => "digit1",
    Digit2 => "digit2",
    Digit3 => "digit3",
    Digit4 => "digit4",
    Digit5 => "digit5",
    Digit6 => "digit6",
    Digit7 => "digit7",
    Digit8 => "digit8",
    Digit9 => "digit9",
    ArrowUp => "arrow_up",
    ArrowDown => "arrow_down",
    ArrowLeft => "arrow_left",
    ArrowRight => "arrow_right",
    ShiftLeft => "shift_left",
    ShiftRight => "shift_right",
    ControlLeft => "control_left",
    ControlRight => "control_right",
    AltLeft => "alt_left",
    AltRight => "alt_right",
    SuperLeft => "super_left",
    SuperRight => "super_right",
    Escape => "escape",
    Enter => "enter",
    Tab => "tab",
    Backspace => "backspace",
    Space => "space",
    CapsLock => "caps_lock",
    F1 => "f1",
    F2 => "f2",
    F3 => "f3",
    F4 => "f4",
    F5 => "f5",
    F6 => "f6",
    F7 => "f7",
    F8 => "f8",
    F9 => "f9",
    F10 => "f10",
    F11 => "f11",
    F12 => "f12",
    Home => "home",
    End => "end",
    PageUp => "page_up",
    PageDown => "page_down",
    Insert => "insert",
    Delete => "delete",
    Backquote => "backquote",
    Backslash => "backslash",
    BracketLeft => "bracket_left",
    BracketRight => "bracket_right",
    Comma => "comma",
    Equal => "equal",
    Minus => "minus",
    Period => "period",
    Quote => "quote",
    Semicolon => "semicolon",
    Slash => "slash",
    Numpad0 => "numpad0",
    Numpad1 => "numpad1",
    Numpad2 => "numpad2",
    Numpad3 => "numpad3",
    Numpad4 => "numpad4",
    Numpad5 => "numpad5",
    Numpad6 => "numpad6",
    Numpad7 => "numpad7",
    Numpad8 => "numpad8",
    Numpad9 => "numpad9",
    NumpadAdd => "numpad_add",
    NumpadDecimal => "numpad_decimal",
    NumpadDivide => "numpad_divide",
    NumpadEnter => "numpad_enter",
    NumpadEqual => "numpad_equal",
    NumpadMultiply => "numpad_multiply",
    NumpadSubtract => "numpad_subtract",
}
