//! Path: native/game_nif/src/key_map.rs
//! Summary: winit KeyCode → Elixir アトム名のマッピング
//!
//! 生イベント転送用。Elixir 側でキー→意味のマッピングを行う。
//!
//! TODO: phf や lazy_static による静的マップ、あるいはマクロでマッピングを定義すると
//! 行数削減と保守性向上が期待できる。

use game_render::window::KeyCode;

/// KeyCode を Elixir アトム名（&str）に変換する。
/// 設計書の {:raw_key, key, state} の key として使用。
#[allow(clippy::too_many_lines)]
pub fn key_code_to_atom_str(code: KeyCode) -> &'static str {
    match code {
        KeyCode::KeyA => "a",
        KeyCode::KeyB => "b",
        KeyCode::KeyC => "c",
        KeyCode::KeyD => "d",
        KeyCode::KeyE => "e",
        KeyCode::KeyF => "f",
        KeyCode::KeyG => "g",
        KeyCode::KeyH => "h",
        KeyCode::KeyI => "i",
        KeyCode::KeyJ => "j",
        KeyCode::KeyK => "k",
        KeyCode::KeyL => "l",
        KeyCode::KeyM => "m",
        KeyCode::KeyN => "n",
        KeyCode::KeyO => "o",
        KeyCode::KeyP => "p",
        KeyCode::KeyQ => "q",
        KeyCode::KeyR => "r",
        KeyCode::KeyS => "s",
        KeyCode::KeyT => "t",
        KeyCode::KeyU => "u",
        KeyCode::KeyV => "v",
        KeyCode::KeyW => "w",
        KeyCode::KeyX => "x",
        KeyCode::KeyY => "y",
        KeyCode::KeyZ => "z",
        KeyCode::Digit0 => "digit0",
        KeyCode::Digit1 => "digit1",
        KeyCode::Digit2 => "digit2",
        KeyCode::Digit3 => "digit3",
        KeyCode::Digit4 => "digit4",
        KeyCode::Digit5 => "digit5",
        KeyCode::Digit6 => "digit6",
        KeyCode::Digit7 => "digit7",
        KeyCode::Digit8 => "digit8",
        KeyCode::Digit9 => "digit9",
        KeyCode::ArrowUp => "arrow_up",
        KeyCode::ArrowDown => "arrow_down",
        KeyCode::ArrowLeft => "arrow_left",
        KeyCode::ArrowRight => "arrow_right",
        KeyCode::ShiftLeft => "shift_left",
        KeyCode::ShiftRight => "shift_right",
        KeyCode::ControlLeft => "control_left",
        KeyCode::ControlRight => "control_right",
        KeyCode::AltLeft => "alt_left",
        KeyCode::AltRight => "alt_right",
        KeyCode::SuperLeft => "super_left",
        KeyCode::SuperRight => "super_right",
        KeyCode::Escape => "escape",
        KeyCode::Enter => "enter",
        KeyCode::Tab => "tab",
        KeyCode::Backspace => "backspace",
        KeyCode::Space => "space",
        KeyCode::CapsLock => "caps_lock",
        KeyCode::F1 => "f1",
        KeyCode::F2 => "f2",
        KeyCode::F3 => "f3",
        KeyCode::F4 => "f4",
        KeyCode::F5 => "f5",
        KeyCode::F6 => "f6",
        KeyCode::F7 => "f7",
        KeyCode::F8 => "f8",
        KeyCode::F9 => "f9",
        KeyCode::F10 => "f10",
        KeyCode::F11 => "f11",
        KeyCode::F12 => "f12",
        KeyCode::Home => "home",
        KeyCode::End => "end",
        KeyCode::PageUp => "page_up",
        KeyCode::PageDown => "page_down",
        KeyCode::Insert => "insert",
        KeyCode::Delete => "delete",
        KeyCode::Backquote => "backquote",
        KeyCode::Backslash => "backslash",
        KeyCode::BracketLeft => "bracket_left",
        KeyCode::BracketRight => "bracket_right",
        KeyCode::Comma => "comma",
        KeyCode::Equal => "equal",
        KeyCode::Minus => "minus",
        KeyCode::Period => "period",
        KeyCode::Quote => "quote",
        KeyCode::Semicolon => "semicolon",
        KeyCode::Slash => "slash",
        KeyCode::Numpad0 => "numpad0",
        KeyCode::Numpad1 => "numpad1",
        KeyCode::Numpad2 => "numpad2",
        KeyCode::Numpad3 => "numpad3",
        KeyCode::Numpad4 => "numpad4",
        KeyCode::Numpad5 => "numpad5",
        KeyCode::Numpad6 => "numpad6",
        KeyCode::Numpad7 => "numpad7",
        KeyCode::Numpad8 => "numpad8",
        KeyCode::Numpad9 => "numpad9",
        KeyCode::NumpadAdd => "numpad_add",
        KeyCode::NumpadDecimal => "numpad_decimal",
        KeyCode::NumpadDivide => "numpad_divide",
        KeyCode::NumpadEnter => "numpad_enter",
        KeyCode::NumpadEqual => "numpad_equal",
        KeyCode::NumpadMultiply => "numpad_multiply",
        KeyCode::NumpadSubtract => "numpad_subtract",
        _ => "unknown",
    }
}
